# Generated by Django 4.2.2 on 2023-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCompetitionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('league', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('club_id', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalty_kicks', models.IntegerField()),
                ('peanlty_goals', models.IntegerField()),
                ('xg', models.FloatField()),
                ('non_penalty_xg', models.FloatField()),
                ('xa', models.FloatField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('progressive_passes', models.IntegerField()),
                ('progressive_carries', models.IntegerField()),
                ('progressive_receives', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLeagueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('league', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('club_id', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalty_kicks', models.IntegerField()),
                ('peanlty_goals', models.IntegerField()),
                ('xg', models.FloatField()),
                ('non_penalty_xg', models.FloatField()),
                ('xa', models.FloatField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('progressive_passes', models.IntegerField()),
                ('progressive_carries', models.IntegerField()),
                ('progressive_receives', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
