# Generated by Django 4.2.2 on 2023-07-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLeagueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('league', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalty_kicks', models.IntegerField()),
                ('penalty_goals', models.IntegerField()),
                ('xg', models.FloatField(null=True)),
                ('non_penalty_xg', models.FloatField(null=True)),
                ('xa', models.FloatField(null=True)),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('progressive_passes', models.IntegerField(null=True)),
                ('progressive_carries', models.IntegerField(null=True)),
                ('progressive_receives', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCompetitionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('league', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalty_kicks', models.IntegerField()),
                ('penalty_goals', models.IntegerField()),
                ('xg', models.FloatField(null=True)),
                ('non_penalty_xg', models.FloatField(null=True)),
                ('xa', models.FloatField(null=True)),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('progressive_passes', models.IntegerField(null=True)),
                ('progressive_carries', models.IntegerField(null=True)),
                ('progressive_receives', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('num_matches_league', models.IntegerField()),
                ('num_matches_comps', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
