# Generated by Django 4.2.2 on 2023-06-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='playerleaguedata',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RemoveField(
            model_name='playercompetitiondata',
            name='club_id',
        ),
        migrations.AlterField(
            model_name='playercompetitiondata',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club'),
        ),
    ]
