# Generated by Django 4.2.2 on 2023-07-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                ("league_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("code", models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="league",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.league"
            ),
        ),
    ]
