# Generated by Django 4.2.2 on 2023-06-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercompetitiondata',
            old_name='peanlty_goals',
            new_name='penalty_goals',
        ),
        migrations.RenameField(
            model_name='playerleaguedata',
            old_name='peanlty_goals',
            new_name='penalty_goals',
        ),
    ]
