# Generated by Django 4.2.2 on 2023-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_league_match_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="confederation",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="league",
            name="country",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
