# Generated by Django 4.2.2 on 2023-07-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_league_confederation_league_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercompetitiondata',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.league'),
        ),
        migrations.AlterField(
            model_name='playerleaguedata',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.league'),
        ),
    ]
